### ISSUE TITLE
ESLint: Unable to resolve path to module 'bunyan-debug-stream'. (import/no-unresolved)

### ISSUE THREAD

**Issue by sbellone** [jwalton/bunyan-debug-stream#15]
Hi! My linter is reporting the above error with the v3.0.
When inspecting the module, I found out that it's probably because in your `package.json`, you have:
```
  "main": "./lib/index.js",
  "types": "./lib/index.d.ts",
```
But since you have no `index.ts` file, the resulting package doesn't have those files.

**Comment by jwalton** [comment]
Oops.  I copy-pasted that from another package.json when I moved this project to typescript.  :(  That's an embarassing error.  Thanks for the issue!
