### ISSUE TITLE
Custom prefixes joiner

### ISSUE THREAD

**Issue by noomorph** [jwalton/bunyan-debug-stream#66]
Hi, this is your fellow happy user from the [wix/Detox](https://wix.github.io/Detox) project. 👋 

**Do you mind if we add a sort of custom function to join prefixes?**

Currently your logic is hardcoded like that: `prefixes => [${prefixes.join(',')]` – I'd like to be able to customize this convention to produce logs like here below:

![image](https://user-images.githubusercontent.com/1962469/187474904-5e241738-5e2f-47d0-9412-a7d996fc3093.png)

P.S. To illustrate the current logic:

![image](https://user-images.githubusercontent.com/1962469/187475703-303cf420-7f08-40ab-b01a-ecca9218a117.png)

**Comment by jwalton** [comment]
Yeah, for sure.  Please feel welcome to submit a PR.  Should be easy to supply a `tagFormat(prefixes: string[]): string` function or something similar to the options. (Also, if I don't get back to you on your PR feel free to harass me every couple of days until I do.  ;)

**Comment by noomorph** [comment]
@jwalton, I prepared the pull request. See #67.
